name: ESPHome Issue Compile

on:
  issues:
    types: [opened, edited]
  workflow_dispatch:
    inputs:
      yaml_config:
        description: 'ESPHome YAML 配置'
        required: true
        type: string

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install ESPHome
        run: |
          pip install esphome

      - name: Get configuration content
        id: config
        uses: actions/github-script@v6
        with:
          script: |
            let yaml = '';
            let issue_number = null;
            
            if (context.eventName === 'issues') {
              // 从 issue 获取配置
              const issue = await github.rest.issues.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.issue.number
              });
              const content = issue.data.body;

              // 提取 YAML 内容 (假设 YAML 内容在 ```yaml 和 ``` 之间)
              const yamlMatch = content.match(/```yaml\s*([\s\S]*?)\s*```/);
              if (!yamlMatch) {
                core.setFailed('No YAML configuration found in issue body');
                return;
              }

              yaml = yamlMatch[1];
              issue_number = context.payload.issue.number;
            } else if (context.eventName === 'workflow_dispatch') {
              // 从手动触发的输入获取配置
              yaml = context.payload.inputs.yaml_config;
              console.log('Received YAML config from manual trigger:', yaml);
            }

            if (!yaml) {
              core.setFailed('No YAML configuration provided');
              return;
            }

            require('fs').writeFileSync('config.yaml', yaml);
            console.log('Written config.yaml with content length:', yaml.length);
            if (issue_number) {
              core.setOutput('issue_number', issue_number);
            }

      - name: Validate and compile ESPHome configuration
        id: compile
        continue-on-error: true
        run: |
          ls -lha
          cat config.yaml
          esphome config config.yaml
          esphome compile config.yaml

      - name: Comment on issue with result
        if: github.event_name == 'issues'
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const compileSuccess = ${{ steps.compile.outcome == 'success' }};

            let comment = '';
            if (compileSuccess) {
              comment = '✅ ESPHome 配置验证和编译成功！';
            } else {
              comment = '❌ ESPHome 配置验证或编译失败，请检查配置。';
            }

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ steps.config.outputs.issue_number }},
              body: comment
            });
